### ISSUE TITLE
 pre-trained diffusion model

### ISSUE THREAD

**Issue by wh277** [kiharalab/DiffModeler#4]
Pre-trained diffusion model was failed to download from the 2 links. Could you please provide a new link, thanks.

**Comment by wang3702** [comment]
I just tested and it works fine. I would guess it is because of the firewall issues. A simple test would be to try https://huggingface.co. If you can not access the hugginface main website, then it is the firewall problem.

**Comment by wh277** [comment]
OK, thanks
